'use client'
import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  value: 0
};

 const counterSlice = createSlice({
  name: 'counter',
  initialState,
  reducers: {
    increment(state) {
      state.value += 1;
    },
    decrement(state) {
      state.value -= 1;
    },
    addby(state, action) {
      state.value += action.payload;
    }
  }
});

// export the actions generated by counterslice
export const { increment, decrement, addby } = counterSlice.actions;
// export the reducer that generated 
export default counterSlice.reducer ;